name: my-brain

services:
  document-api:
    build:
      context: ./services/document-api
    container_name: my-brain-document-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - my-brain

  web:
    build:
      context: ./apps/web
    container_name: my-brain-web
    ports:
      - "4200:4200"
    depends_on:
      - document-api
    networks:
      - my-brain

networks:
  my-brain:
    driver: bridge
